# Generated by Django 4.1 on 2022-08-16 17:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fly', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='customer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ticket',
            name='flight_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fly.flight'),
        ),
        migrations.AddField(
            model_name='flight',
            name='airline_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fly.airlinecompany'),
        ),
        migrations.AddField(
            model_name='flight',
            name='destination_contry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='destination_flights', to='fly.country'),
        ),
        migrations.AddField(
            model_name='flight',
            name='origin_contry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='origin_flights', to='fly.country'),
        ),
        migrations.AddField(
            model_name='airlinecompany',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fly.country'),
        ),
        migrations.AddField(
            model_name='airlinecompany',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
